const stories = [
    "The Hare and the Tortoise\n\n\n\nA Hare was making fun of the Tortoise one day for being so slow.\n\n \"Do you ever get anywhere?\" he asked with a mocking laugh.\n\n \"Yes,\" replied the Tortoise, \"and I get there sooner than you think. I'll run you a race and prove it.\"\n\n The Hare was much amused at the idea of running a race with the Tortoise, but for the fun of the thing he agreed.\n\n So the Fox, who had consented to act as judge, marked the distance and started the runners off.\n\n The Hare was soon far out of sight, and to make the Tortoise feel very deeply how ridiculous it was for him to try a race with a Hare,\n\n he lay down beside the course to take a nap until the Tortoise should catch up.\n\n The Tortoise meanwhile kept going slowly but steadily, and, after a time, passed the place where the Hare was sleeping.\n\n But the Hare slept on very peacefully; and when at last he did wake up, the Tortoise was near the goal.\n\n The Hare now ran his swiftest, but he could not overtake the Tortoise in time.",
    
    "\nA Lion lay asleep in the forest, his great head resting on his paws. \n\n A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose.\n\n Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her.\n\n \"Spare me!\" begged the poor Mouse. \"Please let me go and some day I will surely repay you.\"\n\n The Lion was much amused to think that a Mouse could ever help him. But he was generous and finally let the Mouse go.\n\n Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net.\n\n Unable to free himself, he filled the forest with his angry roaring.\n\n The Mouse knew the voice and quickly found the Lion struggling in the net.\n\n Running to one of the great ropes that bound him, she gnawed it until it parted, and soon the Lion was free.\n\n \"You laughed when I said I would repay you,\" said the Mouse. \"Now you see that even a Mouse can help a Lion.\"",
    
    "The Dog and His Reflection\n\n\n\nA Dog, to whom the butcher had thrown a bone, was hurrying home with his prize as fast as he could go.\n\n As he crossed a narrow footbridge, he happened to look down and saw himself reflected in the quiet water as if in a mirror.\n\n But the greedy Dog thought he saw a real Dog carrying a bone much bigger than his own.\n\n If he had stopped to think he would have known better. But instead of thinking, he dropped his bone and sprang at the Dog in the river,\n\n only to find himself swimming for dear life to reach the shore. At last he managed to scramble out, and as he stood sadly thinking about the good bone he had lost,\n\n he realized what a stupid Dog he had been.",
    
    "The Crow and the Pitcher\n\n\n\nIn a spell of dry weather, when the Birds could find very little to drink,\n\n a thirsty Crow found a pitcher with a little water in it.\n\n But the pitcher was high and had a narrow neck,\n\n and no matter how he tried, the Crow could not reach the water. The poor thing felt as if he must die of thirst.\n\n Then an idea came to him. Picking up some small pebbles, he dropped them into the pitcher one by one.\n\n With each pebble the water rose a little higher until at last it was near enough so he could drink.",
    
    "The Ants and the Grasshopper\n\n\n\nOne bright day in late autumn a family of Ants were bustling about in the warm sunshine,\n\n drying out the grain they had stored up during the summer, when a starving Grasshopper, his fiddle under his arm,\n\n came up and humbly begged for a bite to eat.\n\n \"What!\" cried the Ants in surprise, \"haven't you stored anything away for the winter? What in the world were you doing all last summer?\"\n\n \"I didn't have time to store up any food,\" whined the Grasshopper; \"I was so busy making music that before I knew it the summer was gone.\"\n\n The Ants shrugged their shoulders in disgust. \"Making music, were you?\" they cried. \"Very well; now dance!\"\n\n And they turned their backs on the Grasshopper and went on with their work."
  ]
  
  export default stories