"""Created tables

Revision ID: 7b9470514573
Revises: 
Create Date: 2023-09-28 20:52:39.305046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9470514573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('voice', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('accomodations', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('teacher', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('subjects')
    # ### end Alembic commands ###
